name: Update README on Bucket Change

on:
  push:
    branches:
      - master
    paths:
      - 'bucket/**'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install jq

    - name: Update README
      run: |
        echo "<p align=\"center\">" > README.md
        echo "    <h1 align=\"center\">Scoop Bucket</h1>" >> README.md
        echo "</p>" >> README.md
        echo "<p align=\"center\">" >> README.md
        echo "### SCOOP介绍" >> README.md
        echo "" >> README.md
        echo "Scoop**是一款适用于Windows平台的命令行软件（包）管理工具**。 简单来说，就是可以通过命令行工具（PowerShell、CMD等）实现软件（包）的安装管理等需求，通过简单的一行代码实现软件的下载、安装、卸载、更新等操作。" >> README.md
        echo "" >> README.md
        echo "Scoop bucket **就是一个软件仓库**,提供windows渗透测试环境工具进行快捷安装、管理和自动更新。" >> README.md
        echo "### 软件自动更新" >> README.md
        echo "" >> README.md
        echo "这个仓库已经添加 github ci 自动化，每隔几个小时会自动更新所有软件到最新版本" >> README.md
        echo "" >> README.md
        echo "使用者可以自行在系统中加个定时任务，这样就能自动更新 scoop 软件了，当然也可以手工更新" >> README.md
        echo "" >> README.md
        echo "### scoop基础使用" >> README.md
        echo "" >> README.md
        echo "官网安装说明书： [ScoopInstaller](https://github.com/ScoopInstaller)" >> README.md
        echo "" >> README.md
        echo "1. 先决条件" >> README.md
        echo "" >> README.md
        echo "   - [PowerShell](https://aka.ms/powershell)最新版本或[Windows PowerShell 5.1](https://aka.ms/wmf5download)" >> README.md
        echo "" >> README.md
        echo "2. PowerShell执行策略：" >> README.md
        echo "" >> README.md
        echo "   \`\`\`" >> README.md
        echo "   Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser" >> README.md
        echo "   \`\`\`" >> README.md
        echo "" >> README.md
        echo "3. 下载安装脚本,在Powershell中执行以下命令" >> README.md
        echo "" >> README.md
        echo "   \`\`\`" >> README.md
        echo "   irm get.scoop.sh -outfile 'install.ps1'" >> README.md
        echo "   \`\`\`" >> README.md
        echo "" >> README.md
        echo "4. 管理员执行安装脚本" >> README.md
        echo "" >> README.md
        echo "   \`\`\`" >> README.md
        echo "   .\\install.ps1 -RunAsAdmin -ScoopDir 'D:\\Base' -ScoopGlobalDir 'D:\\Global' -NoProxy" >> README.md
        echo "   \`\`\`" >> README.md
        echo "" >> README.md
        echo "   其中\`-RunAsAdmin\`是使用管理员角色执行脚本，\`-ScoopDir\`指定scoop安装目录，软件默认安装在此。 \`-ScoopGlobalDir\`指定全局程序安装到自定义目录。" >> README.md
        echo "" >> README.md
        echo "## 现有适配软件" >> README.md
        echo "| 软件                            | 描述                                                         | 官网地址                                                     |" >> README.md
        echo "| :------------------------------ | :----------------------------------------------------------- | :----------------------------------------------------------- |" >> README.md
        find bucket -name '*.json' | while read file; do
          name=$(jq -r '.name' "$file")
          description=$(jq -r '.description' "$file")
          homepage=$(jq -r '.homepage' "$file")
          echo "| scoop install $name -g | $description | <$homepage> |" >> README.md
        done

        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Update README with bucket JSON info" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
